### ISSUE TITLE
Bug: `FirestoreCategorizedPictureTest > displayOnWorksAsExpected` fails very often

### ISSUE THREAD

**Issue by Nitwix** [HumanLearning2021/HumanLearningApp#184]
com.github.HumanLearning2021.HumanLearningApp.firestore.FirestoreCategorizedPictureTest > displayOnWorksAsExpected[test(AVD) - 11] FAILED 
	java.lang.AssertionError:
	Expected: not null

**Comment by Nitwix** [comment]
I have a possible fix, not sure if it works yet: https://github.com/HumanLearning2021/HumanLearningApp/pull/154/commits/aa49e43cb702be9c5f666b3b9da9b88ecbb739fe
EDIT : It didn't work

**Comment by bbjubjub2494** [comment]
The root cause of this is that `displayOn` has fire-and-forget semantics. One way to go about this instead of adding delays would be to weave the operation back into the coroutine via a [RequestListener callback](https://bumptech.github.io/glide/javadocs/4110/com/bumptech/glide/RequestBuilder.html#addListener-com.bumptech.glide.request.RequestListener-)
